CREATE TABLE USER2 (
  ID         NUMBER PRIMARY KEY,
  USERNAME          VARCHAR(50) NOT NULL,
  PASSWORD          VARCHAR(50) NOT NULL,
  FIRST_NAME        VARCHAR(50) NOT NULL,
  LAST_NAME         VARCHAR(50) NOT NULL,
  PHONE             VARCHAR(50) NOT NULL,
  LOG_IN_STATUS     CHAR(1) NOT NULL CHECK (LOG_IN_STATUS = 'Y' OR LOG_IN_STATUS = 'N')
)