CREATE TABLE PROPERTY (
  ID         NUMBER PRIMARY KEY,
  AREA              NUMBER NOT NULL,
  ROOMS_QUANTITY    NUMBER NOT NULL,
  REGION            VARCHAR(50) NOT NULL,
  CITY              VARCHAR(50) NOT NULL,
  PROPERTY_TYPE     NVARCHAR2(50) NOT NULL CHECK(PROPERTY_TYPE = 'HOUSE' OR PROPERTY_TYPE = 'APARTMENT'),
  PROPERTY_CLASS    NVARCHAR2(50) NOT NULL CHECK(PROPERTY_CLASS = 'LUXURY' OR PROPERTY_CLASS = 'BUSINESS'OR PROPERTY_CLASS = 'EСONOMY')
)